import { ListingAction, OrderAction, OrderStatus } from 'utils/enums';
import { fiatToToken } from 'utils/helpers';
import { Listing, Order } from 'utils/types';

const myListing1: Listing = {
  id: 14698,
  token: 'USDT',
  action: ListingAction.Buy,
  fiatCurrency: 'USD',
  price: 1.01,
  totalAmount: 100,
  availableAmount: 80,
  minPerOrder: 10,
  maxPerOrder: 200,
  userAddress: '0x1234567890',
  hasOrders: true,
};

const myListing2: Listing = {
  id: 14698,
  token: 'USDT',
  action: ListingAction.Sell,
  fiatCurrency: 'USD',
  price: 1.01,
  totalAmount: 100,
  availableAmount: 80,
  minPerOrder: 10,
  maxPerOrder: 200,
  userAddress: '0x1234567890',
  hasOrders: true,
};

const theirListing1: Listing = {
  id: 14698,
  token: 'USDT',
  action: ListingAction.Buy,
  fiatCurrency: 'USD',
  price: 1.02,
  totalAmount: 230,
  availableAmount: 140,
  minPerOrder: 50,
  maxPerOrder: 230,
  userAddress: '0x54866544843',
  hasOrders: true,
};

const theirListing2: Listing = {
  id: 14698,
  token: 'USDT',
  action: ListingAction.Sell,
  fiatCurrency: 'USD',
  price: 1.02,
  totalAmount: 230,
  availableAmount: 140,
  minPerOrder: 50,
  maxPerOrder: 230,
  userAddress: '0x54866544843',
  hasOrders: true,
};

const orders: Order[] = [
  {
    id: 42000,
    fiatAmount: 100,
    tokenAmount: fiatToToken(100, myListing1),
    status: OrderStatus.RequestSent,
    listing: myListing1,
    action: OrderAction.Sell,
  },
  {
    id: 42001,
    fiatAmount: 100,
    tokenAmount: fiatToToken(100, myListing1),
    status: OrderStatus.AssetsConfirmed,
    listing: myListing1,
    action: OrderAction.Sell,
  },
  {
    id: 42002,
    fiatAmount: 100,
    tokenAmount: fiatToToken(100, myListing1),
    status: OrderStatus.PaymentSent,
    listing: myListing1,
    action: OrderAction.Sell,
  },
  {
    id: 42003,
    fiatAmount: 100,
    tokenAmount: fiatToToken(100, myListing1),
    status: OrderStatus.Completed,
    listing: myListing1,
    action: OrderAction.Sell,
  },
  {
    id: 42004,
    fiatAmount: 100,
    tokenAmount: fiatToToken(100, myListing1),
    status: OrderStatus.InDispute,
    listing: myListing1,
    action: OrderAction.Sell,
  },
  {
    id: 42005,
    fiatAmount: 100,
    tokenAmount: fiatToToken(100, myListing1),
    status: OrderStatus.Cancelled,
    listing: myListing1,
    action: OrderAction.Sell,
  },
  {
    id: 42006,
    fiatAmount: 100,
    tokenAmount: fiatToToken(100, theirListing1),
    status: OrderStatus.RequestSent,
    listing: theirListing1,
    action: OrderAction.Buy,
  },
  {
    id: 42007,
    fiatAmount: 100,
    tokenAmount: fiatToToken(100, theirListing1),
    status: OrderStatus.AssetsConfirmed,
    listing: theirListing1,
    action: OrderAction.Buy,
  },
  {
    id: 42008,
    fiatAmount: 100,
    tokenAmount: fiatToToken(100, theirListing1),
    status: OrderStatus.PaymentSent,
    listing: theirListing1,
    action: OrderAction.Buy,
  },
  {
    id: 42009,
    fiatAmount: 100,
    tokenAmount: fiatToToken(100, theirListing1),
    status: OrderStatus.Completed,
    listing: theirListing1,
    action: OrderAction.Buy,
  },
  {
    id: 42010,
    fiatAmount: 100,
    tokenAmount: fiatToToken(100, theirListing1),
    status: OrderStatus.InDispute,
    listing: theirListing1,
    action: OrderAction.Buy,
  },
  {
    id: 42011,
    fiatAmount: 100,
    tokenAmount: fiatToToken(100, theirListing1),
    status: OrderStatus.Cancelled,
    listing: theirListing1,
    action: OrderAction.Buy,
  },

  {
    id: 42012,
    fiatAmount: 100,
    tokenAmount: fiatToToken(100, myListing2),
    status: OrderStatus.RequestSent,
    listing: myListing2,
    action: OrderAction.Buy,
  },
  {
    id: 42013,
    fiatAmount: 100,
    tokenAmount: fiatToToken(100, myListing2),
    status: OrderStatus.AssetsConfirmed,
    listing: myListing2,
    action: OrderAction.Buy,
  },
  {
    id: 42014,
    fiatAmount: 100,
    tokenAmount: fiatToToken(100, myListing2),
    status: OrderStatus.TokensDeposited,
    listing: myListing2,
    action: OrderAction.Buy,
  },
  {
    id: 42015,
    fiatAmount: 100,
    tokenAmount: fiatToToken(100, myListing2),
    status: OrderStatus.PaymentSent,
    listing: myListing2,
    action: OrderAction.Buy,
  },
  {
    id: 42016,
    fiatAmount: 100,
    tokenAmount: fiatToToken(100, myListing2),
    status: OrderStatus.Completed,
    listing: myListing2,
    action: OrderAction.Buy,
  },
  {
    id: 42017,
    fiatAmount: 100,
    tokenAmount: fiatToToken(100, myListing2),
    status: OrderStatus.InDispute,
    listing: myListing2,
    action: OrderAction.Buy,
  },
  {
    id: 42018,
    fiatAmount: 100,
    tokenAmount: fiatToToken(100, myListing2),
    status: OrderStatus.Cancelled,
    listing: myListing2,
    action: OrderAction.Buy,
  },
  {
    id: 42019,
    fiatAmount: 100,
    tokenAmount: fiatToToken(100, theirListing2),
    status: OrderStatus.RequestSent,
    listing: theirListing2,
    action: OrderAction.Sell,
  },
  {
    id: 42020,
    fiatAmount: 100,
    tokenAmount: 21,
    status: OrderStatus.AssetsConfirmed,
    listing: theirListing2,
    action: OrderAction.Sell,
  },
  {
    id: 42021,
    fiatAmount: 100,
    tokenAmount: fiatToToken(100, theirListing2),
    status: OrderStatus.TokensDeposited,
    listing: theirListing2,
    action: OrderAction.Sell,
  },
  {
    id: 42022,
    fiatAmount: 100,
    tokenAmount: fiatToToken(100, theirListing2),
    status: OrderStatus.PaymentSent,
    listing: theirListing2,
    action: OrderAction.Sell,
  },
  {
    id: 42023,
    fiatAmount: 100,
    tokenAmount: fiatToToken(100, theirListing2),
    status: OrderStatus.Completed,
    listing: theirListing2,
    action: OrderAction.Sell,
  },
  {
    id: 42024,
    fiatAmount: 100,
    tokenAmount: fiatToToken(100, theirListing2),
    status: OrderStatus.InDispute,
    listing: theirListing2,
    action: OrderAction.Sell,
  },
  {
    id: 42025,
    fiatAmount: 100,
    tokenAmount: fiatToToken(100, theirListing2),
    status: OrderStatus.Cancelled,
    listing: theirListing2,
    action: OrderAction.Sell,
  },
];

export default orders;
